## The following functions performs matrix inversion and keeps a cache 
## of the inverse of the matrix to yield the same result without recomputing 
## if the input matrix is not changed. It creates a special object that 
## stores a matrix and cache's its inverse


## function makeCacheMatrix creates a special "Matrix"
## It returns a list containing a function to 1. set the matrix
## 2. get the matrix, 3. set the inverse, and 4. get the inverse

makeCacheMatrix <- function(x = matrix()) {
  # initialise inverse matrix
  inv_x <- NULL
  
  # set function
  set <- function(y) {
    x <<- y
    inv_x <<- NULL
  }
  
  # get function to retrieve the matrix
  get <- function() x
  
  # set function for inverse
  setinv <- function(inv) inv_x <<- inv
  
  # get function to retrieve the inverse
  getinv <- function() inv_x
  
  # return value, i.e. list, of the function
  list(set = set, get = get, setinv = setinv, getinv = getinv)
}


## function cacheSolve solves for the inverse of a "special matrix",
## the kind of format generated by makeCacheMatrix above.
## It first checks to see if the inverse has already been calculated,
## in which case it gets the inverse from the cache and skips computation

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  inv_x <- x$getinv()
  
  # check if cache is available
  if(!is.null(inv_x)) {
    message("getting cached data")
    return(inv_x)
  }
  
  # retrieve matrix
  data <- x$get()
  
  # solve for inverse
  inv_x <- solve(data, ...)
  
  #set inverse matrix
  x$setinv(inv_x)
  inv_x
}